=== App发送验证码:
- URL:  /app/user/sendVerifyCode
- Method:  POST
- 参数:
|==========================================================
|参数名       |描述
|phoneNumber  |接收验证码的手机号码
|==========================================================

- 返回值:
----
{
    "state": 0,
    "msg": "xxxxxxx"
}
----

|==========================================================
|state值     |含义
|0           |发送成功
|4           |请求太频繁(请等待60秒以后再试)
|5           |发送验证码失败
|100         |服务器错误
|==========================================================


=== App用户登录:
- URL: /app/user/login
- Method: POST
- 参数:

|==========================================================
|参数名         |描述
|phoneNumber    |手机号码
|password       |密码
|==========================================================

- 返回值:

----
		{
			"state": 0,
			"msg": null,
			"result": {
                "token": "xxxxxxxxxxxxxxxxxxxxx",
                "userinfo": {
                    "nickname": "xxxxxxxx",
                    "avatar": "http://xxx.xxxxxxxxxx",
                    "phone": "xxxxxxxx",
                    "email": "xxxxxxxxx"
                }
            }
		}
----

=== App用户注册:
- URL:  /app/user/register
- Method: POST
- 参数:
|==========================================================
|参数名      |描述
|phoneNumber |手机号码
|nickName    |用户昵称 (可以为空)
|password    |密码
|verifyCode  |验证码
|email       |邮箱地址 (可以为空)
|==========================================================

- 返回值:
----
{
    "state": 0,
    "msg": "xxxxxxx"
}
----

=== 上传图片：
- URL:  /app/image
- Method: POST
- content-type:  multipart/form-data
- 参数:
|===============================
|参数名      |描述
|sessionId   |登录返回的sessionId
|image       |图片文件内容
|===============================

- 返回值:
----
{
    "imageId": 6,
    "width": 6000,   //原图尺寸
    "height": 2315,   //原图尺寸
    "url": "http://localhost:6060/assets/user/1/D8F219B9D0C0470C961074650E79D3DC/e2fee30d51cc481ab8a4e7f3419014b7.jpg",   //图片url
    "errcode": 0,
    "errmsg": null
}
----

=== 删除上传的图片:
- URL:  /app/image?imageId=xxx&sessionId=xxxx
- Method: DELETE
- 返回值:

----
{
    "errcode" : 0,
    "errmsg" : null
}
----

=== 重置密码:
- URL:  /app/user/resetPassword
- Method: POST
- 参数:
|==========================================================
|参数名       |描述
|phoneNumber  |手机号码
|verifyCode   |上一个请求中发到用户手机上的验证码
|newPassword  |新密码
|==========================================================

- 返回值:

----
{
    "state" : 0,
    "msg" : null
}
----

=== 使用条款:
- URL:  /app/license
- Method: GET
- 返回值 content-type: text/html
- 返回值内容: 使用条款html文本


=== 常见问题:
- URL:  /app/faq
- Method: GET
- 返回值: content-type: text/html
- 返回值内容: 常见问题html文本

=== 检查app版本 (android)
- URL:  /app/client
- Method: GET
- 返回值:

----
        {
            "version":"0719",
            "fileName":"JoySpace_client-0719.apk"
        }
----
- apk下载地址:    /assets/app/<fileName>


=== 获取同城的所有自助机
- URL:  /app/printStation/findByCity
- Method: GET
- 参数:
|==========================================================
|参数名      |描述
|longitude  |位置精度(double)
|latitude   |位置纬度(double)
|==========================================================

- 返回值:
----
        {
				"state" : 0,
				"msg" : null,
                "result": [
                    {
                        "id": x,
                        "name": "xxx",
                        "address": "xxxxx",
                        "longitude": xxxxx,
                        "latitude": xxxx,
                        "transportation": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
                    },
                    {
                        "id": x,
                        "name": "xxx",
                        "address": "xxxxx",
                        "longitude": xxxxx,
                        "latitude": xxxx,
                        "transportation": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
                    },
                    ...
                    {
                        "id": x,
                        "name": "xxx",
                        "address": "xxxxx",
                        "longitude": xxxxx,
                        "latitude": xxxx,
                        "transportation": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
                    }
                ]
        }
----

=== 获取最近的自助机
- URL:  /app/printStation/nearest
- Method: GET
- 参数:
|==========================================================
|参数名      |描述
|longitude  |位置精度(double)
|latitude   |位置纬度(double)
|==========================================================

- 返回值:
----
        {
				"state" : 0,
				"msg" : null,
                "result": {
                    "id": x,
                    "name": "xxx",
                    "address": "xxxxx",
                    "longitude": xxxxx,
                    "latitude": xxxx,
                    "transportation": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
                }
        }
----

=== 自助机详情
- URL:  /app/printStation/{id}
- Method: GET
- 参数:
|==========================================================
|参数名   | 描述
|id      | 自助机id
|==========================================================

- 返回值:

----
		{
			"address": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", 地址
			"longitude" : xxxx.xxx,   //经度
			"latitude": xxxx.xxx,     //纬度
			"products": [             //产品列表
				{
					"id": xx,
					"name": "xxx",
					"type": x,   //0 普通   1 证件照    2 模板拼图
					"width": xxx.xx,   //产品宽度(毫米)
					"height": xxx.xx,   //产品高度(毫米)
					"imageCount": x,    //需要用户上传的照片张数
					"version": xx,      //版本号(整数)
					"previewUrls": [     //产品预览图片url （可能有多个)
						"https://xxx.xxxxxxxxxxxxxxxxxxxxxxxxxx",
						"https://xxx.xxxxxxxxxxxxxxxxxxxxxxxxxx",
						"https://xxx.xxxxxxxxxxxxxxxxxxxxxxxxxx"
					],
					"thumbnailUrl": "https://xxx.xxxxxxxxxxxxxxxxxxxxxxxxxx",   //缩略图url
					"price": xxx,   //产品价格（整数，单位是分）
					"remark": "xxxxxxxxxxxxxxxxxxxxxxxxxxx"      //产品说明文本
				},
				{ ... },
				{ ... }
			]
		}
----

=== App主页数据:
- URL:  /app/homepage
- 返回值:

----
{
        "msg" : "OK",
        "state" : 0,
        "result" : {
                "promote" : [
                        {
                                "name" : "广告1",
                                "describe" : "广告描述1",
                                "contentUrl" : "https://test.uni-colour.com/assets/app/images/ad1.jpg"
                        },
                        {
                                "name" : "广告2",
                                "describe" : "广告描述2",
                                "contentUrl" : "https://test.uni-colour.com/assets/app/images/ad2.jpg"
                        }
                ],
                "productory" : [
                        {
                                "id" : 0,
                                "name" : "普通照片",
                                "describe" : "首次冲印免费",
                                "iconUrl" : "https://test.uni-colour.com/assets/app/images/photo.jpg",
                                "startColor" : "#ffda48",
                                "endColor" : "#ffbc2c"
                        },
                        {
                                "id" : 1,
                                "name" : "证件照",
                                "describe" : "首次冲印免费",
                                "iconUrl" : "https://test.uni-colour.com/assets/app/images/id_photo.jpg",
                                "startColor" : "#fca9c3",
                                "endColor" : "#fd798e"
                        },
                        {
                                "id" : 2,
                                "name" : "模板拼图",
                                "describe" : "免费模板随便用",
                                "iconUrl" : "https://test.uni-colour.com/assets/app/images/template_photo.jpg",
                                "startColor" : "#f6c3fc",
                                "endColor" : "#ccb0fd"
                        }
                ]
        }
}

----
