=== 微信用户登录:
- URL: /api/user/login
- Method: POST
- 参数:
|==========================================================
|参数名       |描述
|code         |小程序调用 wx.login 获得的登录凭证
|==========================================================

- 返回值:
----
    {
        "errcode": 0,
		"errmsg": null,
		"sessionId": "c96aa7ff47c941b881ba068faf7b617c"
	}
----

=== 微信用户信息注册:
- URL: /api/user/reg
- Method: POST
- RequestBody:
----
		{
			"nickName" : "xxxx",
			"avatarUrl" : "xxxx",
			"gender" : x,
			"province" : "xxxx",
			"city" : "xxxx"
			"country" : "xxxx"
		}
----

- 返回值:
----
    {
        "errcode" : 0,
        "errmsg" : null
    }
----


=== 根据二维码查找自助打印机

返回的自助打印机信息中包含支持的产品列表

- URL: /api/printStation/findByQrCode
- Method: GET
- 参数:
|==========================================================
|参数名       |描述
|qrCode      |小程序扫到的自助机二维码
|==========================================================

- 返回值:

----
{
    "id": 1,
    "address": "北京市海淀区大柳树路17号富海中心2号富海大厦509",
    "wxQrCode": "https://test.uni-colour.com/printStation/1",
    "longitude": 116.33511,
    "latitude": 39.95392,
    "products": [
        {
            "id": 1,                //产品ID
            "name": "1寸照片",
            "type": 1,              //产品类型 0: 普通照片, 1: 证件照, 2: 模板拼图
            "templateWidth": 101.6,         //模板宽度 (毫米)
            "templateHeight": 152.39999,    //模板高度 (毫米)
            "width": xx,  //证件照返回头像宽度,其他类型的产品返回模板宽度（毫米）
            "height": xx,  //证件照返回头像高度,其他类型的产品返回模板高度（毫米）
            "displaySize" : "25 x 35 mm",   //显示用的尺寸 (证件照这个尺寸是头像图片框的尺寸， 其他类型的产品是模板的尺寸)
            "idPhotoMaskImageUrl": "https://xxx.xxxxxxx.xxx/xxxxx.png",       //证件照头像轮廓图片url(其他类型产品此项为null)
            "imageRequired": 1,     //需要上传的图片数量
            "remark": "",
            "price": 1,             //价格 (分)
            "version": "3.11",           //版本号
            "thumbnailImageUrl": "http://xxxxxxxxxxxxx",               //缩略图url
            "previewImageUrls": [                   //预览图url列表
                "http://xxxxxxxxxxxxx",
                "http://xxxxxxxxxxxxx",
                "http://xxxxxxxxxxxxx"
            ],
            "templateImages": [
                {
                    "name": "照片",                                                      //图片名称， 名称相同的图片用户图片只需要用户上传同一张图
                    "x": 11.300000190734863,                                              //图片框位置和尺寸(单位毫米)
                    "y": 3.1999969482421875,
                    "width": 25,
                    "height": 35,
                    "isUserImage": true,                                                 //是否是需要用户上传的图片
                    "url": "http://localhost:6060/assets/template/preview/3_v11/images/UserImagePlaceHolder.png"
                },
                {
                    "name": "照片",
                    "x": 65.29999542236328,
                    "y": 3.1999969482421875,
                    "width": 25,
                    "height": 35,
                    "isUserImage": true,
                    "url": "http://localhost:6060/assets/template/preview/3_v11/images/UserImagePlaceHolder.png"
                },
                ...
                {
                    "name": "照片",
                    "x": 65.29999542236328,
                    "y": 114.19999694824219,
                    "width": 25,
                    "height": 35,
                    "isUserImage": true,
                    "url": "http://localhost:6060/assets/template/preview/3_v11/images/UserImagePlaceHolder.png"
                }
            ]
        }
        ...
    ]
}
----

=== 根据id查找自助打印机

返回的自助打印机信息中包含支持的产品列表

- URL: /api/printStation/{id}
- Method: GET
- 参数:
|==========================================================
|参数名       |描述
|id          |自助机id
|==========================================================

- 返回值:  和根据二维码查找自助打印机接口相同


=== 上传图片：
- URL: /api/image
- Method: POST
- content-type:  multipart/form-data
- 参数:
|==========================================================
|参数名       |描述
|sessionId    |登录返回的sessionId
|image        |图片文件内容
|==========================================================
- 返回值:

----
           {
               "errcode": 0,        //错误代码, 0表示成功
               "errmsg": null,
               "imageId": xxx,
               "width": xxxx,        //宽度和高度
               "height": xxxx,
               "url": "http://xxxxxxxxxxxxxxxx.jpg"
           }
----

=== 删除上传的图片:
- URL: /api/image?imageId=xxx&sessionId=xxxx
- Method: DELETE
- 返回值:
----
			{
				"errcode" : 0,
				"errmsg" : null
			}
----


=== 生成成品的预览图：
- URL: /api/product/preview
- Method: POST
- content-type:  application/json
- 参数: (POST body， json格式)
----
        {
            "sessionId": "xxxxxxxxxxxxxxxxxxxx",
            "productId": xx,              //产品id
            "productVersion" : "xx.xx",   //产品版本号
            "images" : [
                {
                    "imageId": xxx,  //上传图片接口返回的图片id
                    "name": "xxx",    //模板中的用户图片名称
                    "initialRotate" : 0,   //图片初始旋转角度，必须是 0, 90, 180, 270 中的某一个
                    "scale": 1.0,          //图片缩放比例
                    "rotate: 0.0,          //图片旋转角度
                    "horTranslate": 0.0,     //图片水平移动距离，单位mm
                    "verTranslate": 0.0,     //图片垂直移动距离，单位mm
                    "brightness": 1.0,       //亮度调整 (0~2), 数值为1时保持不变
                    "saturate": 1.0,         //饱和度调整 (0~2), 数值为1时保持不变
                    "effect": "none",        //图片效果, none: 没有,  grayscale: 黑白图片效果,  sepia: 怀旧效果
                },
                {
                    ...
                },
                {
                    ...
                },
                ...
            ]
        }
----

- 返回: (json 对象)
----
        {
            "errcode": 0,
            "errmsg": null,
            "svgUrl": "https://xxxxxxxxxxxxxxxxxxxxxxxxx.svg",   //这个是给app用的svg格式的模板
            "jpgUrl": "https://xxxxxxxxxxxxxxxxxxxxxxxxx.jpg"    //jpg格式预览图
        }
----

==== 查询自助机耗材是否足够打印指定的订单:
==== (目前这个接口返回的数据是假的, 如果有 copies > 10 的订单项，返回值中的canPrint就为false)
- URL: /api/order/check
- Method: POST
- RequestBody:

----
		{
		  "sessionId" : "xxxxxxxxx",
		  "printStationId" : xx,        //自助机id
		  "orderItems" : [
			{
				"productId" : xx,       //产品id
				"productVersion" : "xx.xx",  //产品版本号
				"copies": xx            //打印份数 (>=1)
			},
			{
			    "productId" : xx,
			    "productVersion" : "xx.xx",
			    "copies": xx
			},
			{
			    "productId" : xx,
			    "productVersion" : "xx.xx",
			    "copies": xx
			}
			...
		  ],
		  "couponId": 0              //优惠券id (0表示不使用优惠券)
		}
----

- 返回:

----
	{
		"errcode" : 0,
		"errmsg": null,
		"canPrint": true,    //true表示printStationId对应的自助机可以打印此订单, false表示耗材不足，需要提示用户换自助机
		"totalFee": xxx,     //总价, 单位为分
		"discount": xxx      //折扣, 单位为分,  总价-折扣 为用户应支付的价格
	}
----

==== 创建订单:
- URL: /api/order/create
- Method: POST
- RequestBody:

----
		{
		  "sessionId" : "xxxxxxxxx",
		  "printStationId" : xx,        //自助机id
		  "orderItems" : [
			{
				"productId" : xx,       //产品id
				"productVersion" : "xx.xx",  //产品版本号
				"copies": xx            //打印份数 (>=1)
			},
			{
			    "productId" : xx,
			    "productVersion" : "xx.xx",
			    "copies": xx
			},
			{
			    "productId" : xx,
			    "productVersion" : "xx.xx",
			    "copies": xx
			}
			...
		  ],
		  "couponId": 0              //优惠券id (0表示不使用优惠券)
		}
----

- 返回:

----
	{
		"errcode" : 0,
		"errmsg": null,
		"wxPayParams": {
			"timeStamp" : "1499865120",
			"nonceStr": "asdfasdfasdfas",
			"pkg": "prepay_id=wx23423452345dfgl",
			"paySign" : "6354ldgsgadfas"
		},
        "totalFee": xxx,     //总价, 单位为分
        "discount": xxx,      //折扣, 单位为分,  总价-折扣 为用户应支付的价格
		"orderItems" {                 //和请求中的 orderItems 对应
		    {
		        "id": xx,              //订单项id
		        "productId" : xx       //产品id
		    },
		    {
		        "id": xx,
		        "productId" : xx
		    },
		    ...
		}
	}
----

==== 上传订单图片文件:
- URL: /api/order/image
- Method: POST
- content-type:  multipart/form-data
- 参数:
|==========================================================
|参数名         |描述
|sessionId     |登录返回的sessionId
|orderItemId   |创建订单接口返回的订单项id
|name          |图片名称
|image         |图片文件内容
|initialRotate |图片初始旋转角度，必须是 0, 90, 180, 270 中的某一个
|scale         |图片缩放比例
|rotate        |图片旋转角度
|horTranslate  |图片水平移动距离，单位mm
|verTranslate  |图片垂直移动距离，单位mm
|brightness    |亮度调整 (0~2), 数值为1时保持不变
|saturate      |饱和度调整 (0~2), 数值为1时保持不变
|effect        |图片效果, none: 没有,  grayscale: 黑白图片效果,  sepia: 怀旧效果
|==========================================================

- 返回值:

----
           {
               "errcode": 0,        //错误代码, 0表示成功
               "errmsg": null,
               "allImagesUploaded": true    //true表示整个订单所有的用户图片都已经上传完成, false 表示还有未上传的用户图片文件
           }
----

==== 返回用户优惠券列表
- URL: /api/user/coupons
- Method: GET
- 参数:
|==========================================================
|参数名         |描述
|sessionId     |登录返回的sessionId
|==========================================================

- 返回值:

----
           {
                "errcode": 0,        //错误代码, 0表示成功
                "errmsg": null,
                "coupons": [
                    {
                        "id": 1,                 //优惠券id
                        "name": "xxxxxxxxxx",    //名称
                        "code": "xxxxxxx"        //编码
                        "begin": "yyyy-MM-dd HH:mm:ss",  //生效日期时间
                        "expire": "yyyy-MM-dd HH:mm:ss", //失效日期时间
                        "minExpense": 1000,             //使用优惠券所需要的最小金额（分）
                        "discount": 200                 //折扣金额（分）
                    },
                    ...
               ]
           }
----

==== 用户领取优惠券
- URL: /api/user/claimCoupon
- Method: POST
- 参数:
|==========================================================
|参数名         |描述
|sessionId      |登录返回的sessionId
|couponCode     |优惠券代码
|==========================================================

- 返回值:

----
           {
                "errcode": 0,        //错误代码, 0表示成功
                "errmsg": null,
                "coupon": {
                    "id": 1,                 //优惠券id
                    "name": "xxxxxxxxxx",    //名称
                    "code": "xxxxxxx"        //编码
                    "begin": "yyyy-MM-dd HH:mm:ss",  //生效日期时间
                    "expire": "yyyy-MM-dd HH:mm:ss", //失效日期时间
                    "minExpense": 1000,             //使用优惠券所需要的最小金额（分）
                    "discount": 200                 //折扣金额（分）
                }
           }
----