=== 微信用户登录:
- URL: /api/user/login
- Method: POST
- 参数:
|==========================================================
|参数名       |描述
|code         |小程序调用 wx.login 获得的登录凭证
|==========================================================

- 返回值:
----
    {
        "errcode": 0,
		"errmsg": null,
		"sessionId": "c96aa7ff47c941b881ba068faf7b617c"
	}
----

=== 微信用户信息注册:
- URL: /api/user/reg
- Method: POST
- RequestBody:
----
		{
			"nickName" : "xxxx",
			"avatarUrl" : "xxxx",
			"gender" : x,
			"province" : "xxxx",
			"city" : "xxxx"
			"country" : "xxxx"
		}
----

- 返回值:
----
    {
        "errcode" : 0,
        "errmsg" : null
    }
----


=== 根据二维码查找自助打印机

返回的自助打印机信息中包含支持的产品列表

- URL: /api/printStation/findByQrCode
- Method: GET
- 参数:
|==========================================================
|参数名       |描述
|qrCode      |小程序扫到的自助机二维码
|==========================================================

- 返回值:

----
{
    "id": 1,
    "address": "北京市海淀区大柳树路17号富海中心2号富海大厦509",
    "wxQrCode": "https://test.uni-colour.com/printStation/1",
    "longitude": 116.33511,
    "latitude": 39.95392,
    "products": [
        {
            "id": 1,                //产品ID
            "name": "1寸照片",
            "type": 1,              //产品类型 0: 普通照片, 1: 证件照, 2: 模板拼图
            "width": 101.6,         //宽度 (毫米)
            "height": 152.39999,    //高度 (毫米)
            "imageRequired": 1,     //需要上传的图片数量
            "remark": "",
            "price": 1,             //价格 (分)
            "version": 1,           //版本号
            "thumbnailImageUrl": "http://xxxxxxxxxxxxx",               //缩略图url
            "previewImageUrls": [                   //预览图url列表
                "http://xxxxxxxxxxxxx",
                "http://xxxxxxxxxxxxx",
                "http://xxxxxxxxxxxxx"
            ],
            "templateImages": [
                {
                    "name": "照片",                                                      //图片名称， 名称相同的图片用户图片只需要用户上传同一张图
                    "x": 11.300000190734863,                                              //图片框位置和尺寸(单位毫米)
                    "y": 3.1999969482421875,
                    "width": 25,
                    "height": 35,
                    "isUserImage": true,                                                 //是否是需要用户上传的图片
                    "url": "http://localhost:6060/assets/template/preview/3_v11/images/UserImagePlaceHolder.png"
                },
                {
                    "name": "照片",
                    "x": 65.29999542236328,
                    "y": 3.1999969482421875,
                    "width": 25,
                    "height": 35,
                    "isUserImage": true,
                    "url": "http://localhost:6060/assets/template/preview/3_v11/images/UserImagePlaceHolder.png"
                },
                ...
                {
                    "name": "照片",
                    "x": 65.29999542236328,
                    "y": 114.19999694824219,
                    "width": 25,
                    "height": 35,
                    "isUserImage": true,
                    "url": "http://localhost:6060/assets/template/preview/3_v11/images/UserImagePlaceHolder.png"
                }
            ]
        }
        ...
    ]
}
----

=== 根据id查找自助打印机

返回的自助打印机信息中包含支持的产品列表

- URL: /api/printStation/{id}
- Method: GET
- 参数:
|==========================================================
|参数名       |描述
|id          |自助机id
|==========================================================

- 返回值:  和根据二维码查找自助打印机接口相同

=== 查找指定自助打印机支持的产品列表
- URL: /api/product/findByPrintStation
- Method: GET
- 参数:
|==========================================================
|参数名       |描述
|printStationId          |自助机id
|==========================================================

- 返回值:
----
[
    {
        "id": 1,                //产品ID
        "name": "六寸照片",
        "type": 0,              //产品类型 0: 普通照片, 1: 证件照, 2: 模板拼图
        "width": 101.6,         //宽度 (毫米)
        "height": 152.39999,    //高度 (毫米)
        "imageRequired": 1,     //需要上传的图片数量
        "remark": "",
        "price": 1,             //价格 (分)
        "version": 1,           //版本号
        "thumbnailUrls": [                //缩略图url
            "http://xxxxxxxxxxxxx",
            "http://xxxxxxxxxxxxx",
            "http://xxxxxxxxxxxxx"
        ],
        "previewUrls": [                   //预览图url
            "http://xxxxxxxxxxxxx",
            "http://xxxxxxxxxxxxx",
            "http://xxxxxxxxxxxxx"
        ]
    }
    ...
]

----


=== 上传图片： (上传原图和缩略图都用这个)
- URL: /api/image
- Method: POST
- content-type:  multipart/form-data
- 参数:
|==========================================================
|参数名       |描述
|sessionId    |登录返回的sessionId
|image        |图片文件内容
|==========================================================
- 返回值:

----
           {
               "errcode": 0,        //错误代码, 0表示成功
               "errmsg": null,
               "imageId": xxx,
               "width": xxxx,        //宽度和高度
               "height": xxxx,
               "url": "http://xxxxxxxxxxxxxxxx.jpg"
           }
----

=== 缩放图片:
- URL: /api/image/resize
- Method: POST
- 参数:

|==========================================================
|参数名       |描述
|sessionId    |登录返回的sessionId
|width        |要缩放到的宽度(像素)
|height       |要缩放到的高度(像素)
|imageId      |要缩放的图片的id
|==========================================================

- 返回值:

----
         {
             "errcode": 0,
             "errmsg": null,
             "imageId": xx,   //缩放后的新图片的id
             "width": xxx,    //新图片宽度(像素)
             "height": xxx,   //新图片高度(像素)
             "url": "http://xxxxxxxxxxxx.jpg"
         }
----

=== 删除上传的图片:
- URL: /api/image?imageId=xxx&sessionId=xxxx
- Method: DELETE
- 返回值:
----
			{
				"errcode" : 0,
				"errmsg" : null
			}
----


=== 获取产品需要上传的图片的信息:
- URL: /api/product/images
- Method: GET
- 参数:
|==========================================================
|参数名       |描述
|productId    |产品id
|==========================================================
- 返回值: (json数组)

----
    [
        {
            "name": "照片1",
            "width": 100,    //单位mm
            "height": 200    //单位mm
        },
        {
            "name": "照片2",
            "width": 80,
            "height": 60
        },
        ...
    ]
----

=== 生成成品的预览图：
- URL: /api/product/preview
- Method: POST
- content-type:  application/json
- 参数: (POST body， json格式)
----
        {
            "sessionId": "xxxxxxxxxxxxxxxxxxxx",
            "productId": xx,
            "images" : [
                {
                    "imageId": xxx,  //上传图片接口返回的图片id
                    "name": "xxx",    //模板中的用户图片名称
                    "initialRotate" : 0,   //图片初始旋转角度，必须是 0, 90, 180, 270 中的某一个
                    "scale": 1.0,          //图片缩放比例
                    "rotate: 0.0,          //图片旋转角度
                    "horTranslate": 0.0,     //图片水平移动距离，单位mm
                    "verTranslate": 0.0,     //图片垂直移动距离，单位mm
                    "brightness": 1.0,       //亮度调整 (0~2), 数值为1时保持不变
                    "saturate": 1.0,         //饱和度调整 (0~2), 数值为1时保持不变
                    "effect": "none",        //图片效果, none: 没有,  grayscale: 黑白图片效果,  sepia: 怀旧效果
                },
                {
                    ...
                },
                {
                    ...
                },
                ...
            ]
        }
----

- 返回: (json 对象)
----
        {
            "errcode": 0,
            "errmsg": null,
            "svgUrl": "https://xxxxxxxxxxxxxxxxxxxxxxxxx.svg",   //这个是给app用的svg格式的模板
            "jpgUrl": "https://xxxxxxxxxxxxxxxxxxxxxxxxx.jpg"    //jpg格式预览图
        }
----



==== 下单:
- URL: /api/order
- Method: POST
- RequestBody:

----
		{
		  "sessionId" : "xxxxxxxxx",
		  "printStationId" : x,
		  "orderItems" : {
			{
				"productId" : x,
				"imageFileId" : x,
				"copies": x
			},
			{ "productId" : x, "imageFileId" : x, "copies": x },
			{ "productId" : x, "imageFileId" : x, "copies": x }
			...
		  }
		}
----

- 返回:

----
	{
		"errcode" : 0,
		"errmsg": null,
		"wxPayParams": {
			"timeStamp" : "1499865120",
			"nonceStr": "asdfasdfasdfas",
			"pkg": "prepay_id=wx23423452345dfgl",
			"paySign" : "6354ldgsgadfas"
		}
	}
----